CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

create table USER
(
    ID BIGINT not null
        primary key,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    BIRTH DATE,
    MAIL VARCHAR(255)
);
